version: '3'

services:
  nodeapp:
    container_name: nodeapp
    entrypoint: dockerize -wait tcp://mysql-db:3306 -timeout 30s docker-entrypoint.sh node index.js
    build: 
      context: node
    tty: true
    volumes:
      - ./node:/app
    networks:
      - nodenet
    depends_on:
      - mysql-db

  mysql-db:
    container_name: mysql-db
    build:
      context: mysql
    command: --innodb-use-native-aio=0
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=1234
    tty: true
    networks:
      - nodenet

  nginx-server:
    container_name: nginx-server
    build:
      context: nginx
    restart: always
    ports:
      - "8080:80"
    networks:
      - nodenet

networks:
  nodenet:
    driver: bridge